module "create-cluster" {
  source = "./create-cluster"

  tenant_id                                   = var.tenant_id
  network_clientid                            = local.network_sp_client_id
  network_clientsecret                        = local.network_sp_client_secret
  network_client_object_id                    = local.network_sp_object_id
  subnet_id                                   = local.platform_subnet_id
  kubernetes_admin_group_object_ids           = var.kubernetes_admin_group_object_ids
  location                                    = var.location
  resource_group                              = var.resource_group
  cluster_name                                = var.cluster_name
  project_stage                               = var.project_stage
  project_name                                = var.project_name
  customer_name                               = var.customer_name
  cost_center                                 = var.cost_center
  kubernetes_version                          = var.kubernetes_version
  kubernetes_max_db_instances                 = var.kubernetes_max_db_instances
  kubernetes_min_db_instances                 = var.kubernetes_min_db_instances
  kubernetes_max_services_instances           = var.kubernetes_max_services_instances
  kubernetes_max_monitoring_instances         = var.kubernetes_max_monitoring_instances
  kubernetes_min_monitoring_instances         = var.kubernetes_min_monitoring_instances
  kubernetes_max_highmemory_compute_instances = var.kubernetes_max_highmemory_compute_instances
  kubernetes_max_highcpu_compute_instances    = var.kubernetes_max_highcpu_compute_instances
  kubernetes_max_basic_compute_instances      = var.kubernetes_max_basic_compute_instances
  kubernetes_db_type                          = var.kubernetes_db_type
  kubernetes_services_type                    = var.kubernetes_services_type
  kubernetes_monitoring_type                  = var.kubernetes_monitoring_type
  kubernetes_highmemory_compute_type          = var.kubernetes_highmemory_compute_type
  kubernetes_highcpu_compute_type             = var.kubernetes_highcpu_compute_type
  kubernetes_basic_compute_type               = var.kubernetes_basic_compute_type
  kubernetes_nodepool_system_type             = var.kubernetes_nodepool_system_type
  kubernetes_network_plugin                   = var.kubernetes_network_plugin
  temporary_name_for_rotation_system_pool     = var.temporary_name_for_rotation_system_pool
  kubernetes_min_services_instances           = var.kubernetes_min_services_instances
  kubernetes_min_highmemory_compute_instances = var.kubernetes_min_highmemory_compute_instances
  kubernetes_min_basic_compute_instances      = var.kubernetes_min_basic_compute_instances
  kubernetes_min_system_instances             = var.kubernetes_min_system_instances
  kubernetes_max_system_instances             = var.kubernetes_max_system_instances
  kubernetes_max_monitoring_pods              = var.kubernetes_max_monitoring_pods
  kubernetes_max_db_pods                      = var.kubernetes_max_db_pods
  kubernetes_max_highmemory_pods              = var.kubernetes_max_highmemory_pods
  kubernetes_max_services_pods                = var.kubernetes_max_services_pods
  kubernetes_max_basic_pods                   = var.kubernetes_max_basic_pods
  kubernetes_max_highcpu_pods                 = var.kubernetes_max_highcpu_pods
  kubernetes_max_system_pods                  = var.kubernetes_max_system_pods
  kubernetes_basic_enable_auto_scaling        = var.kubernetes_basic_enable_auto_scaling
  kubernetes_db_enable_auto_scaling           = var.kubernetes_db_enable_auto_scaling
  kubernetes_highcpu_enable_auto_scaling      = var.kubernetes_highcpu_enable_auto_scaling
  kubernetes_highmemory_enable_auto_scaling   = var.kubernetes_highmemory_enable_auto_scaling
  kubernetes_monitoring_enable_auto_scaling   = var.kubernetes_monitoring_enable_auto_scaling
  kubernetes_services_enable_auto_scaling     = var.kubernetes_services_enable_auto_scaling
  kubernetes_system_enable_auto_scaling       = var.kubernetes_system_enable_auto_scaling
  kubernetes_db_os_disk_size                  = var.kubernetes_db_os_disk_size
  kubernetes_highcpu_os_disk_size             = var.kubernetes_highcpu_os_disk_size
  kubernetes_basic_os_disk_size               = var.kubernetes_basic_os_disk_size
  kubernetes_highmemory_os_disk_size          = var.kubernetes_highmemory_os_disk_size
  kubernetes_monitoring_os_disk_size          = var.kubernetes_monitoring_os_disk_size
  kubernetes_services_os_disk_size            = var.kubernetes_services_os_disk_size
  kubernetes_system_os_disk_size              = var.kubernetes_system_os_disk_size
  kubernetes_min_highcpu_compute_instances    = var.kubernetes_min_highcpu_compute_instances
  kubernetes_nodepool_system_name             = var.kubernetes_nodepool_system_name
  kubernetes_azure_rbac_enabled               = var.kubernetes_azure_rbac_enabled
  kubernetes_tekton_compute_type              = var.kubernetes_tekton_compute_type
  kubernetes_max_tekton_pods                  = var.kubernetes_max_tekton_pods
  kubernetes_max_tekton_compute_instances     = var.kubernetes_max_tekton_compute_instances
  kubernetes_min_tekton_compute_instances     = var.kubernetes_min_tekton_compute_instances
  kubernetes_tekton_enable_auto_scaling       = var.kubernetes_tekton_enable_auto_scaling
  kubernetes_tekton_os_disk_size              = var.kubernetes_tekton_os_disk_size
  kubernetes_tekton_deploy                    = var.kubernetes_tekton_deploy
  temporary_name_for_rotation_basic_pool      = var.temporary_name_for_rotation_basic_pool
  temporary_name_for_rotation_db_pool         = var.temporary_name_for_rotation_db_pool
  temporary_name_for_rotation_highcpu_pool    = var.temporary_name_for_rotation_highcpu_pool
  temporary_name_for_rotation_highmemoty_pool = var.temporary_name_for_rotation_highmemoty_pool
  temporary_name_for_rotation_monitoring_pool = var.temporary_name_for_rotation_monitoring_pool
  temporary_name_for_rotation_services_pool   = var.temporary_name_for_rotation_services_pool
  temporary_name_for_rotation_tekton_pool     = var.temporary_name_for_rotation_tekton_pool
  kubernetes_cluster_admin_group_object_ids   = var.kubernetes_cluster_admin_group_object_ids

  depends_on = [
    module.create-platform-prerequisite,
    module.create-network,
    module.create-privatedns,
  ]
}
