global:
  enabled: true
  namespace: ${NAMESPACE}

controller:
  replicas: ${REPLICAS}

defaultVaultConnection:
  enabled: true
  address: ${VAULT_ADDR}

defaultAuthMethod:
  enabled: true
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: vault-secrets-operator
  allowedNamespaces: ${ALLOWED_NAMESPACES}

rbac:
  create: true
  serviceAccount:
    create: false
    name: vault-secrets-operator

crd:
  create: true

vaultConnection:
  enabled: true
  address: ${VAULT_ADDR}
  skipTLSVerify: false

vaultAuth:
  enabled: true
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: vault-secrets-operator