loki:
  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: "${LOKI_PERSISTENCE_MEMORY}"
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h
promtail:
  config:
    snippets:
      pipelineStages:
      - cri: {}
      - match:
          action: drop
          pipeline_name: keep only workflows logs
          selector: '{container!="main"}'
  tolerations:
    - effect: NoSchedule
      operator: Exists
