server:
  replicas: ${REPLICAS}
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ingress:
    enabled: ${CREATE_INGRESS}
    ingressClassName: "nginx"
    extraHosts:
      - name: ${ARGOCD_DNS_NAME}
        path: /argocd
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"

  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

configs:
  params:
    server.insecure: true
    server.rootpath: "/argocd"
    server.basehref: "/argocd"
